site_name: ZKWeb框架文档
repo_url: https://github.com/zkweb-framework
copyright: Copyright © 2016 303248153@github
theme_dir: docs_theme
use_directory_urls: false

pages:
- 框架入门:
  - 框架介绍: index.md
  - 创建项目: core/create_project.md
  - 开发项目: core/start_project.md
  - 发布网站: core/publish_website.md
- 核心功能:
  - 网站结构: core/website_struct.md
  - 配置文件: core/website_config.md
  - IoC容器: core/ioc_container.md
  - 插件系统: core/plugin.md
  - 控制器: core/controller.md
  - 请求和错误处理: core/http_handlers.md
  - 模板引擎: core/template_engine.md
  - 动态内容: core/dynamic_contents.md
  - 缓存处理: core/cache.md
  - 文件储存: core/file_storage.md
  - 数据库: core/database.md
  - 多语言: core/multi_language.md
  - 多时区: core/multi_timezone.md
  - 单元测试: core/unit_test.md
- 插件:
  - 基础插件 (Common.Base):
    - 关于基础插件: plugin/common.base.summary.md
    - 通用配置: plugin/common.base.generic_config.md
    - 定时任务: plugin/common.base.scheduled_task.md
    - 会话: plugin/common.base.session.md
    - 基础css样式: plugin/common.base.css.md
    - 基础javascript脚本: plugin/common.base.javascript.md
    - 基础图标字体: plugin/common.base.font.md
    - 仓储和工作单元: plugin/common.base.repository_uow.md
    - 特征接口: plugin/common.base.traits.md
    - 动态表格构建器: plugin/common.base.ajax_table.md
    - 静态表格构建器: plugin/common.base.static_table.md
    - 表单构建器: plugin/common.base.form_builder.md
    - 静态文件处理器: plugin/common.base.static_handler.md
    - 语言时区处理器: plugin/common.base.locale_handler.md
    - 提供的模板文件: plugin/common.base.templates.md
    - 提供的标签和过滤器: plugin/common.base.tag_and_filter.md
    - 提供的隔离策略: plugin/common.base.cache_policy.md
  - 验证码 (Common.Captcha): plugin/common.captcha.md
  - 管理员 (Common.Admin):
    - 用户和角色权限: plugin/common.admin.user_and_role.md
    - 管理后台: plugin/common.admin.admin_panel.md
    - 特征接口: plugin/common.admin.traits.md
    - 添加后台功能: plugin/common.admin.add_simple_app.md
    - 添加增删查改功能: plugin/common.admin.add_crud_app.md
  - 菜单页 (Common.MenuPage): plugin/common.menupage.md
  - 管理员设置 (Common.AdminSettings): plugin/common.adminsettings.md
  - 用户中心 (Common.UserPanel): plugin/common.userpanel.md
  - 联系人 (Common.UserContact): plugin/common.usercontact.md
  - 通用分类 (Common.GenericClass): plugin/common.genericclass.md
  - 通用标签 (Common.GenericTag): plugin/common.generictag.md
  - 通用记录 (Common.GenericRecord): plugin/common.genericrecord.md
  - 语言切换器 (Common.LanguageSwitcher): plugin/common.languageswitcher.md
  - 货币 (Common.Currency): plugin/common.currency.md
  - 伪静态 (Common.PesudoStatic): plugin/common.pesudostatic.md
  - 地区 (Common.Region): plugin/common.region.md
  - 流水号 (Common.SerialGenerate): plugin/common.serialgenerate.md
  - 支付 (Finance.Payment): plugin/finance.payment.md
  - 支付宝 (Finance.Payment.Alipay): plugin/finance.payment.alipay.md
  - 现金支付 (Finance.Payment.Cash): plugin/on_working.md
  - 货到付款 (Finance.Payment.OnArrive): plugin/on_working.md
  - 财付通 (Finance.Payment.Tenpay): plugin/finance.payment.tenpay.md
  - 微信支付 (Finance.Payment.WeChat): plugin/finance.payment.wechat.md
  - Ping++支付 (Finance.Payment.Pingpp): plugin/finance.payment.pingpp.md
  - CKEditor (CMS.CKEditor): plugin/cms.ckeditor.md
  - 图片管理器 (CMS.ImageBrowser): plugin/cms.imagebrowser.md
  - 文章 (CMS.Article): plugin/cms.atricle.md
  - 商品 (Shopping.Product): plugin/shopping.product.md
  - 物流 (Shopping.Logistics): plugin/shopping.logistics.md
  - 订单 (Shopping.Order): plugin/shopping.order.md
  - 售后 (Shopping.AfterSales): plugin/shopping.aftersales.md
  - 商品收藏 (Shopping.ProductBookmark): plugin/on_working.md
  - 商品评论 (Shopping.ProductRating): plugin/on_working.md
  - 多商城 (Multishop.Base): plugin/on_working.md
  - 多商城商品 (Multishop.Product): plugin/on_working.md
  - 多商城物流 (Multishop.Logistics): plugin/on_working.md
  - 多商城订单 (Multishop.Order): plugin/on_working.md
  - 多商城售后 (Multishop.AfterSales): plugin/on_working.md
  - 网页测试运行器 (UnitTest.WebTester): plugin/unittest.webtester.md
  - 手机版布局 (Theme.Mobile.Frame): plugin/theme.mobile.frame.md
  - 商品模板模块 (Theme.Widgets.Product): plugin/on_working.md
  - 轮播图模板模块 (Theme.Widgets.Slideshow): plugin/on_working.md
  - 自定义翻译 (Common.CustomTranslate): plugin/common.customtranslate.md

extra:
    font:
        text: "微软雅黑"
        code: "微软雅黑"
    author:
        github: "zkweb-framework"
