site_name: ZKWeb框架文档
repo_url: https://github.com/zkweb-framework
copyright: Copyright © 2016 303248153@github
theme_dir: docs_theme

pages:
- 框架入门:
  - 框架介绍: index.md
  - 创建项目: core/create_project.md
  - 开发项目: core/start_project.md
  - 发布网站: core/publish_website.md
- 核心功能:
  - 网站结构: core/website_struct.md
  - 配置文件: core/website_config.md
  - IoC容器: core/ioc_container.md
  - 插件系统: core/plugin.md
  - 控制器: core/controller.md
  - 请求和错误处理: core/http_handlers.md
  - 模板引擎: core/template_engine.md
  - 动态内容: core/dynamic_contents.md
  - 缓存隔离: core/isolated_cache.md
  - 数据库: core/database.md
  - 多语言: core/multi_language.md
  - 多时区: core/multi_timezone.md
  - 单元测试: core/unit_test.md
- 插件改版中:
  - 插件改版中，完成后会重写文档: plugin/on_working.md

extra:
    font:
        text: "微软雅黑"
        code: "微软雅黑"
    author:
        github: "zkweb-framework"
