site_name: ZKWeb框架文档

pages:
- 框架介绍:                        index.md
- 首次运行:                        core/gettingstart.md
- 插件系统:                        core/plugin.md
- 控制器和模板系统:                 core/controller.md
- 本地化:                          core/localize.md
- 数据库管理:                      core/database.md
- 单元测试:                        core/unittest.md
- 插件(Common.Base):               plugin/common.base.md
- 插件(Common.Captcha):            plugin/common.captcha.md
- 插件(Common.Admin):              plugin/common.admin.md
- 插件(Common.MenuPageBase):       plugin/common.menupagebase.md
- 插件(Common.AdminSettings):      plugin/common.adminsettings.md
- 插件(Common.UserPanel):          plugin/common.userpanel.md
- 插件(Common.UserContact):        plugin/common.usercontact.md
- 插件(Common.GenericClass):       plugin/common.genericclass.md
- 插件(Common.GenericTag):         plugin/common.generictag.md
- 插件(Common.GenericRecord):      plugin/common.genericrecord.md
- 插件(Common.LanguageSwitcher):   plugin/common.languageswitcher.md
- 插件(Common.Currency):           plugin/common.currency.md
- 插件(Common.Region):             plugin/common.region.md
- 插件(Common.SerialGenerate):     plugin/common.serial.md
- 插件(Finance.Payment):           plugin/common.payment.md
- 插件(Finance.Payment.Alipay):    plugin/common.payment.alipay.md
- 插件(Finance.Payment.Tenpay):    plugin/common.payment.tenpay.md
- 插件(Finance.Payment.WeChat):    plugin/common.payment.wechat.md
- 插件(CMS.CKEditor):              plugin/cms.ckeditor.md
- 插件(CMS.ImageBrowser):          plugin/cms.imagebrowser.md
- 插件(CMS.Article):               plugin/cms.atricle.md
- 插件(Shopping.Product):          plugin/shopping.product.md
- 插件(Shopping.Logistics):        plugin/shopping.logistics.md
- 插件(Shopping.Order):            plugin/shopping.order.md
- 插件(Shopping.AfterSales):       plugin/shopping.aftersales.md
- 插件(UnitTest.WebTester):        plugin/unittest.webtester.md
- 插件(Common.CustomTranslate):    plugin/common.customtranslate.md

theme: material

extra:
    font:
        text: "微软雅黑"
        code: "微软雅黑"
    palette:
        primary: "blue grey"
        accent: "blue grey"
    author:
        github: "zkweb-framework"

markdown_extensions:
    - codehilite(css_class=code)
