site_name: ZKWeb框架文档
repo_url: https://github.com/zkweb-framework
copyright: Copyright © 2016 303248153@github
theme_dir: docs_theme

pages:
- 框架入门:
  - 框架介绍: index.md
  - 创建项目: core/create_project.md
  - 开发项目: core/start_project.md
  - 发布网站: core/publish_website.md
- 核心功能:
  - 网站结构: core/website_struct.md
  - 配置文件: core/website_config.md
  - IoC容器: core/ioc_container.md
  - 插件系统: core/plugin.md
  - 控制器: core/controller.md
  - 请求和错误处理: core/http_handlers.md
  - 模板引擎: core/template_engine.md
  - 动态内容: core/dynamic_contents.md
  - 缓存隔离: core/isolated_cache.md
  - 数据库: core/database.md
  - 多语言: core/multi_language.md
  - 多时区: core/multi_timezone.md
  - 单元测试: core/unit_test.md
- 插件:
  - 基础插件 (Common.Base):
    - 关于基础插件: plugin/common.base.summary.md
    - 通用配置: plugin/common.base.generic_config.md
    - 定时任务: plugin/common.base.scheduled_task.md
    - 会话: plugin/common.base.session.md
    - 基础css样式: plugin/common.base.css.md
    - 基础javascript脚本: plugin/common.base.javascript.md
    - 基础图标字体: plugin/common.base.font.md
    - 仓储和工作单元: plugin/common.base.repository_uow.md
    - 特征接口: plugin/common.base.traits.md
    - 动态表格构建器: plugin/common.base.ajax_table.md

extra:
    font:
        text: "微软雅黑"
        code: "微软雅黑"
    author:
        github: "zkweb-framework"
